baseURL = "https://kondoumh.com/"
languageCode = "ja-jp"
title = "kondoumh"
theme = "ananke"

MetaDataFormat = "yaml"
DefaultContentLanguage = "ja"
SectionPagesMenu = "main"
Paginate = 1 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = "UA-5618326-5"
enableRobotsTXT = true
enableGitInfo = true
disableKinds = ["RSS"]

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  description = "kondoumh home page. write about software I made."
  images = ["/images/mh.png"]
  facebook = ""
  twitter = "https://twitter.com/kondoumh"
  instagram = ""
  youtube = ""
  github = "https://github.com/kondoumh"
  gitlab = ""
  linkedin = ""
  mastodon = ""
  hatenablog = "https://blog.kondoumh.com"
  tumblr = "https://reblog.kondoumh.com"
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/1500x500.jpeg"
  recent_posts_number = 0
  custom_css = ["css/custom.css"]