baseURL = "https://kondoumh.com/"
languageCode = "ja-jp"
title = "kondoumh home"
theme = "ananke"

MetaDataFormat = "yaml"
DefaultContentLanguage = "ja"
SectionPagesMenu = "main"
Paginate = 1 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  # filename = "sitemap.xml"

[params]
  favicon = ""
  description = "The last theme you'll ever need. Maybe."
  facebook = ""
  twitter = "https://twitter.com/kondoumh"
  instagram = ""
  youtube = ""
  github = "https://github.com/kondoumh"
  gitlab = ""
  linkedin = ""
  mastodon = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/1500x500.jpeg"
  recent_posts_number = 2