name: publish Site

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: install hugo
      run: |
        curl -L https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_linux-64bit.tar.gz | tar -xz
        sudo mv hugo /usr/local/bin/hugo
      env:
        HUGO_VERSION: 0.57.2

    - name: checkout
      uses: actions/checkout@v1
      with:
        submodules: true

    - name: generate
    - run: HUGO_ENV=production hugo

    - name: archive
      uses: actions/upload-artifact@master
      with:
        name: public
        path: ./public
